# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signup.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(480, 441)
        self.log_form = QtWidgets.QLabel(Dialog)
        self.log_form.setGeometry(QtCore.QRect(150, 30, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.log_form.setFont(font)
        self.log_form.setObjectName("log_form")
        self.text_u_name = QtWidgets.QLineEdit(Dialog)
        self.text_u_name.setGeometry(QtCore.QRect(170, 110, 261, 31))
        self.text_u_name.setObjectName("text_u_name")
        self.u_name = QtWidgets.QLabel(Dialog)
        self.u_name.setGeometry(QtCore.QRect(40, 110, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.u_name.setFont(font)
        self.u_name.setObjectName("u_name")
        self.pass1 = QtWidgets.QLabel(Dialog)
        self.pass1.setGeometry(QtCore.QRect(40, 160, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.pass1.setFont(font)
        self.pass1.setObjectName("pass")
        self.text_pass = QtWidgets.QLineEdit(Dialog)
        self.text_pass.setGeometry(QtCore.QRect(170, 160, 261, 31))
        self.text_pass.setObjectName("text_pass")
        self.text_u_name_2 = QtWidgets.QLineEdit(Dialog)
        self.text_u_name_2.setGeometry(QtCore.QRect(170, 220, 261, 31))
        self.text_u_name_2.setObjectName("text_u_name_2")
        self.u_name_2 = QtWidgets.QLabel(Dialog)
        self.u_name_2.setGeometry(QtCore.QRect(40, 220, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.u_name_2.setFont(font)
        self.u_name_2.setObjectName("u_name_2")
        self.pass_2 = QtWidgets.QLabel(Dialog)
        self.pass_2.setGeometry(QtCore.QRect(40, 270, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.pass_2.setFont(font)
        self.pass_2.setObjectName("pass_2")
        self.text_pass_2 = QtWidgets.QLineEdit(Dialog)
        self.text_pass_2.setGeometry(QtCore.QRect(170, 270, 261, 31))
        self.text_pass_2.setObjectName("text_pass_2")
        self.u_name_3 = QtWidgets.QLabel(Dialog)
        self.u_name_3.setGeometry(QtCore.QRect(40, 320, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.u_name_3.setFont(font)
        self.u_name_3.setObjectName("u_name_3")
        self.text_u_name_3 = QtWidgets.QLineEdit(Dialog)
        self.text_u_name_3.setGeometry(QtCore.QRect(170, 320, 261, 31))
        self.text_u_name_3.setObjectName("text_u_name_3")
        self.signUp = QtWidgets.QPushButton(Dialog)
        self.signUp.setGeometry(QtCore.QRect(320, 380, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.signUp.setFont(font)
        self.signUp.setObjectName("signUp")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(40, 70, 391, 16))
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "SIGN UP FORM"))
        self.log_form.setText(_translate("Dialog", "Create Account"))
        self.u_name.setText(_translate("Dialog", "Name"))
        self.pass1.setText(_translate("Dialog", "Username"))
        self.u_name_2.setText(_translate("Dialog", "Email"))
        self.pass_2.setText(_translate("Dialog", "Password"))
        self.u_name_3.setText(_translate("Dialog", "Confirm Password"))
        self.signUp.setText(_translate("Dialog", "Sign Up"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

